name: koko
favicon: null
layout_spectrum: 0.34558309195563197
typography_spectrum: 0.8348836367949843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6646255112718791
  lightness: 0.6845009243115783
  saturation: 0.9445156361907721
  rhythmicContrast: 0.10849475557915866
purpose: []
