name: koko
favicon: null
layout_spectrum: 1
typography_spectrum: 0
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Koko
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020504'
    - '#FFFFFC'
    - '#A36542'
    - '#FBB46E'
    - '#4B5D91'
  brandStrength: 0.3125
  lightness: 0.6845009243115783
  saturation: 0.9445156361907721
  rhythmicContrast: 0.1084947555791587
purpose: []
